const mongoose = require("mongoose");
const fs = require("fs");
const path = require("path");
const Product = require("./models/Product");
const Seller = require("./models/Seller");
const User = require("./models/User");
const bcrypt = require("bcryptjs");
const dotenv = require("dotenv");
const connectDB = require("./config/db");

dotenv.config();

const SOURCE_DIR = "C:\\Users\\madhu\\.gemini\\antigravity\\brain\\bc401b15-5bf9-4836-99c8-bcd8c0544e1b\\";
const DEST_DIR = path.join(__dirname, "uploads");

// The exact filenames generated by the AI
const images = {
  smartphone: "premium_smartphone_1774783883503.png",
  earbuds: "wireless_earbuds_1774783902263.png",
  watch: "smart_watch_1774783935693.png",
  charger: "fast_charger_1774783985768.png"
};

const robustSeed = async () => {
  try {
    // 1. Copy Images
    console.log("Copying generated images to uploads directory...");
    if (!fs.existsSync(DEST_DIR)) {
      fs.mkdirSync(DEST_DIR, { recursive: true });
    }

    for (const [key, filename] of Object.entries(images)) {
      const srcPath = path.join(SOURCE_DIR, filename);
      const destPath = path.join(DEST_DIR, filename);
      if (fs.existsSync(srcPath)) {
        fs.copyFileSync(srcPath, destPath);
        console.log(`Copied ${filename}`);
      } else {
        console.log(`WARNING: Source image not found: ${srcPath}`);
      }
    }

    // 2. Connect to DB using App Logic
    console.log("Connecting to database...");
    await connectDB();
    console.log("Connected Successfully.");

    // 3. Find or Create Seller
    let seller = await Seller.findOne({ isApproved: true });
    
    if (!seller) {
      console.log("No approved seller found. Creating a test seller...");
      const hashedPassword = await bcrypt.hash("password123", 10);
      const user = await User.create({
        name: "Premium Vendor",
        email: "vendor@test.com",
        password: hashedPassword,
        role: "seller",
      });
      seller = await Seller.create({
        user: user._id,
        businessName: "Premium Gadgets Ltd",
        gstNumber: "GST123456789",
        isApproved: true,
      });
    }

    // 4. Create Products
    console.log("Clearing old dummy products to avoid clutter...");
    await Product.deleteMany({ brand: { $in: ["Apple", "Samsung", "OnePlus", "Aura"] } });

    console.log("Seeding Premium Products...");
    const newProducts = [
      {
        seller: seller._id,
        title: "Aura X1 Titanium Flagship (256GB)",
        description: "The ultimate minimalist smartphone. Forged from aerospace-grade titanium, featuring a bezel-less 120Hz OLED and an ultra-clear 200MP sensor. Pure elegance.",
        price: 98000,
        mrp: 105000,
        stock: 50,
        category: "Mobiles & Gadgets",
        subCategory: "Mobiles",
        brand: "Aura",
        images: [images.smartphone]
      },
      {
        seller: seller._id,
        title: "Aura SoundPods Pro",
        description: "High-fidelity wireless audio. Seamless white finish with active noise cancellation and spatial sound.",
        price: 18900,
        mrp: 24900,
        stock: 120,
        category: "Mobiles & Gadgets",
        subCategory: "Earbuds",
        brand: "Aura",
        images: [images.earbuds]
      },
      {
        seller: seller._id,
        title: "Aura Chronos Smartwatch",
        description: "Minimalist engineering on your wrist. Seamless silicon band perfectly integrated with a glowing curved AMOLED face. Tracks everything, distracts from nothing.",
        price: 34999,
        mrp: 39999,
        stock: 40,
        category: "Mobiles & Gadgets",
        subCategory: "Wearables",
        brand: "Aura",
        images: [images.watch]
      },
      {
        seller: seller._id,
        title: "Aura 65W GaN Dual-Port Charger",
        description: "Sleek, incredibly powerful, and impossibly small. Fast-charge your smartphone and laptop simultaneously. Braided cable included.",
        price: 3499,
        mrp: 4999,
        stock: 200,
        category: "Mobiles & Gadgets",
        subCategory: "Chargers",
        brand: "Aura",
        images: [images.charger]
      }
    ];

    await Product.insertMany(newProducts);
    console.log("Database Seeded Successfully! Premium images and products are live.");
    process.exit(0);

  } catch (err) {
    console.error("SEEDING CRASHED:", err);
    process.exit(1);
  }
};

robustSeed();
